#! /bin/sh

set -e
set -x

while read -r package action; do
    fedpkg clone "$package"
    cd "$package"
    if test -z "$action"; then
        # by default bump version and build
        msg="rebuild for libpq ABI fix rhbz#1908268"
        rpmdev-bumpspec -c "$msg" *.spec
        git add *.spec
        git commit -m "rebuild for libpq ABI fix

Related: rhbz#1908268"
        git push
    fi

    fedpkg build --target=f34-build-side-37021 --nowait
    cd ..
done < list
